const authTokens = {
  accessToken:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsInJvbGUiOlsiUk9MRV9VU0VSIl0sImlhdCI6MTcxOTgzNTYwMCwiZXhwIjozMzEzNDc0NTYwMH0.IRTLMZRIL2BekooQX1k_28brEjaRrRgGOtVehrLTNv0',
  refreshToken:
    'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QGVtYWlsLmNvbSIsInJvbGUiOiJST0xFX1VTRVIiLCJpYXQiOjE3MjA1Nzc5MTAsImV4cCI6MTcyMDY2NDMxMH0.9qnHjePKA9nRzQWmABJva8urHNv4OYRKBzgDmBnppTg',
};

export default authTokens;
